spring:
  application:
    name: config-server  # Nombre del microservicio
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mateo-404/PriceScout-Microservices-API  # Repositorio Git donde están las configs
          search-paths: config/dev  # Carpeta dentro del repo donde buscar las configs
server:
  port: 8888  # Puerto del Config Server