server:
    port: 8888 # Puerto estándar para Config Server
spring:
    application:
        name: config-sv
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Mateo-404/PriceScout-Microservices-API.git
                    search-paths: config/dev
                    clone-on-start: true
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            register-with-eureka: true
            fetch-registry: true